stages:
  - preparation
  - test


# Variables
variables:
  DB_USERNAME: $MYSQL_USER
  DB_PASSWORD: $MYSQL_PASSWORD
  DB_DATABASE: $MYSQL_DATABASE
  DB_HOST: $MYSQL_HOST

cache:
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"

composer:
  stage: preparation
  tags: 
    - dev
    - vds5

  script:
    - php -v
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
    - cp .env.example .env
    - php artisan key:generate
  artifacts:
    paths:
      - vendor/
      - .env
    expire_in: 1 days
    when: always
  cache:
    paths:
      - vendor/

npm:
  stage: preparation
  tags: 
    - dev
    - vds5
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/
    expire_in: 1 days
    when: always
  cache:
    paths:
      - node_modules/    

test:
  stage: test
  tags:
    - dev
    - vds5
    
  script:
    - php artisan migrate:refresh --seed
    #- ./vendor/phpunit/phpunit/phpunit -v --coverage-text --colors=never --stderr
