# Variables
variables:
  MYSQL_ROOT_PASSWORD: bPdl016KAqvZqdoGVVJG
  MYSQL_USER: admin
  MYSQL_PASSWORD: "!LmP9p7jGwyP"
  MYSQL_DATABASE: dev-db
  DB_HOST: dev-test-mysql-1.c1venzhec3tj.eu-central-1.rds.amazonaws.com

test:
  stage: test
  services:
    - mysql:5.5
  #image: edbizarro/gitlab-ci-pipeline-php:7.4-alpine
  script:
    - yarn install --pure-lockfile
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress
    #- cp .env.example .env
    #- php artisan key:generate
    #- php artisan migrate:refresh --seed
    - ./vendor/phpunit/phpunit/phpunit -v --coverage-text --colors=never --stderr
