# GitLab CI help:      <https://docs.gitlab.com/ee/ci/yaml/>
# GitLab environments: <https://docs.gitlab.com/ee/ci/variables/>
#
# IMPORTANT NOTICES:
# 1. You should make an protected tags rules in repository. Rules list:
# - Tag "*"; Allowed to create "No one"
# - Tag "v*.*.*"; Allowed to create "Maintainers"
# 2. You should make "Push Rule" - "Branch name" regex `[a-z0-9\/\-]+`
# 3. You should protect `master` branch - push for "Maintainers" only

stages:
  - preparation
  - building
  - deploy

# Variables
variables:
  DB_USERNAME: $DB_USERNAME
  DB_PASSWORD: $DB_PASSWORD
  DB_DATABASE: $DB_DATABASE
  DB_HOST: $DB_HOST
  CI_DEBUG_TRACE: "true"

# inherit all global cache settings
cache: &global_cache
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - vendor/
    - node_modules/    
  policy: pull-push

composer:
  stage: preparation
  script:
    - php -v
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
    - cp .env.example .env
    - php artisan key:generate
  artifacts:
    paths:
      - .env
    expire_in: 2 hrs
    when: always

yarn:
  stage: preparation
  script:
    - yarn --version
    - yarn install --pure-lockfile

build-assets:
  stage: building
  # Download the artifacts for these jobs
  dependencies:
    - composer
  script:
    - yarn --version
    - yarn run production --progress false
  artifacts:
    paths:
      - public/css/
      - public/js/
      - public/fonts/
      - public/mix-manifest.json
    expire_in: 1 days
    when: always
  cache:
    <<: *global_cache
    policy: pull

db-seeding:
  stage: building
  services:
    - name: mysql:8.0
      command: ["--default-authentication-plugin=mysql_native_password"]
  # Download the artifacts for these jobs
  dependencies:
    - composer
  script:
    - mysql --version
    - php artisan migrate:fresh --seed
    - mysqldump --host="${DB_HOST}" --user="${DB_USERNAME}" --password="${DB_PASSWORD}" "${DB_DATABASE}" > db.sql
  artifacts:
    paths:
      - storage/logs # for debugging
      - db.sql
    expire_in: 1 days
    when: always
  cache:
    <<: *global_cache
    policy: pull

deploy-test:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
  environment:
    name: testing
    url: https://dev.ukvp.ru
  tags: 
    - dev
    - vds5
  dependencies:
    - composer
  script:
    - dep deploy testing --tag=$CI_COMMIT_REF_NAME -vvv
  cache:
    <<: *global_cache
    policy: pull
    
