stages:
  - prepare
  - test


# Variables
variables:
  DB_USERNAME: $MYSQL_USER
  DB_PASSWORD: $MYSQL_PASSWORD
  DB_DATABASE: $MYSQL_DATABASE
  DB_HOST: $MYSQL_HOST

prepare:
  stage: prepare
  tags: 
    - development
    - vds5
  variables:
    GIT_CLONE_PATH: $CI_BUILDS_DIR/ukvp.ru

  script:
    - npm install

test:
  stage: test
  tags:
    - dev
    - vds5
  variables:
    GIT_CLONE_PATH: $CI_BUILDS_DIR/ukvp.ru
    
  script:
    - npm install
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress
    - cp .env.example .env
    - php artisan key:generate
    - php artisan migrate:refresh --seed
    #- ./vendor/phpunit/phpunit/phpunit -v --coverage-text --colors=never --stderr
