# Variables
variables:
  MYSQL_USER: $MYSQL_USER
  MYSQL_PASSWORD: $MYSQL_PASSWORD
  MYSQL_DATABASE: $MYSQL_DATABASE
  DB_HOST: $MYSQL_HOST

test:
  stage: test
  tags:
    - dev
    - vds5
  variables:
    GIT_CLONE_PATH: $CI_BUILDS_DIR/ukvp.ru
    
  script:
    - npm install
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress
    - cp .env.example .env
    - php artisan key:generate
    - php artisan migrate:refresh --seed
    #- ./vendor/phpunit/phpunit/phpunit -v --coverage-text --colors=never --stderr
