# Variables
variables:
  MYSQL_ROOT_PASSWORD: bPdl016KAqvZqdoGVVJG
  MYSQL_USER: admin
  MYSQL_PASSWORD: "!LmP9p7jGwyP"
  MYSQL_DATABASE: dev-db
  DB_HOST: dev-test-mysql-1.c1venzhec3tj.eu-central-1.rds.amazonaws.com

test:
  stage: test
  tags:
    - dev
    - vds5
  variables:
    GIT_CLONE_PATH: $CI_BUILDS_DIR/ukvp.ru
    
  script:
    - npm install
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress
    #- cp .env.example .env
    #- php artisan key:generate
    #- php artisan migrate:refresh --seed
    #- ./vendor/phpunit/phpunit/phpunit -v --coverage-text --colors=never --stderr
    - chown -R www-data"www-data $CI_BUILDS_DIR/ukvp.ru/storage
    - chown -R www-data"www-data $CI_BUILDS_DIR/ukvp.ru/public
    - chmod -R a+w $CI_BUILDS_DIR/ukvp.ru/public
    - chmod -R a+w $CI_BUILDS_DIR/ukvp.ru/public
    - npm run dev
